import assert from 'node:assert/strict';
import {Game} from './dist/engine.js';
import {migrateSave,settleRun,careerProgress,buyUpgrade,SHOP} from './dist/progression.js';
const migrated=migrateSave({coins:230,vitality:2,power:3,reload:4,best:6});assert.equal(migrated.reload,4);assert.equal(migrated.coins,230);assert.equal(migrated.careerXp,0);
const game=new Game();game.enemies=[{id:1,type:0,x:130,y:180,hp:0,maxHp:50,speed:0,damage:1,attack:1,burn:0,slow:0,flash:0}];game.spawnTotal=10;game.wave=1;game.step(.01);assert.equal(game.kills,1);assert.equal(game.loot.length,1);assert.equal(game.gold,0);assert.equal(game.xp,0);game.state='upgrade';game.step(.1);assert.equal(game.loot[0].age,0);game.state='playing';for(let i=0;i<9;i++)game.step(.1);assert.equal(game.loot.length,0);assert.equal(game.gold,1);assert.equal(game.xp,3);assert.equal(game.totalXp,3);
const save=migrateSave({coins:20,careerXp:149});game.loot.push({id:9,x:0,y:0,age:0,xp:6,coins:4});game.state='retired';let r=settleRun(save,game);assert.equal(r.coins,5);assert.equal(r.xp,9);assert.equal(save.coins,25);assert.equal(save.careerXp,158);assert.equal(careerProgress(save.careerXp).level,2);settleRun(save,game);assert.equal(save.coins,25);assert.equal(save.careerXp,158);
const base=new Game(),personal=new Game({hero:1,meta:{fpower:2,fskill:3}});assert.ok(personal.team[0].damage>32);assert.equal(personal.team[0].burn,14);const wallet=migrateSave({coins:1000});assert.ok(buyUpgrade(wallet,'fskill'));assert.equal(wallet.fskill,1);assert.equal(wallet.coins,945);assert.equal(buyUpgrade(wallet,'invalid'),false);assert.ok(SHOP.some(d=>d.key==='reload'&&d.hero===0));
const shield=new Game();shield.shield=100;for(let i=0;i<100;i++)shield.step(.1);assert.equal(shield.houseTimer,0);shield.shield=0;shield.houseTimer=21.99;shield.step(.02);assert.equal(shield.shield,100);assert.equal(shield.houseTimer,0);
const choice=new Game();choice.xp=choice.nextXp;choice.checkLevel();let index=choice.options.findIndex(o=>o.id.startsWith('recruit'));choice.choose(index);assert.equal(choice.team.length,2);assert.ok(choice.team[1].upgrades.length);assert.ok(choice.upgradeLog.length);
for(const speed of [1,2,3]){const g=new Game();for(let frame=0;frame<30/speed;frame++)for(let step=0;step<speed;step++)g.step(.01);assert.ok(Math.abs(g.time-.3)<.00001);}
console.log('PASS: delayed loot, pause safety, exact-once collection and settlement, career XP, legacy save migration, personal purchases, shield timing, recruitment logs, 1x/2x/3x stepping.');
