import assert from 'node:assert/strict';
import {Game} from './dist/engine.js';
const rng=()=>{let s=123456;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}};
const g=new Game({random:rng()});assert.equal(g.team.length,1);g.xp=g.nextXp;g.checkLevel();assert.equal(g.state,'upgrade');assert.equal(g.options.length,3);const hp=g.hp,t=g.time;g.step(.1);assert.equal(g.time,t);assert.equal(g.hp,hp);const r=g.options.findIndex(o=>o.id.startsWith('recruit'));assert.ok(r>=0);g.choose(r);assert.equal(g.team.length,2);assert.equal(g.state,'playing');
for(let hero=0;hero<4;hero++){
 const a=new Game({hero,random:rng()});let choices=0;for(let i=0;i<90000;i++){
 if(a.state==='upgrade'){assert.equal(a.options.length,3);assert.equal(new Set(a.options.map(o=>o.id)).size,3);const ranked=a.options.map((o,i)=>({i,score:o.id.startsWith('recruit')?100:o.id==='wall'&&a.hp/a.maxHp<.55?95:o.id==='team'?80:o.id==='combo'?85:o.id.startsWith('damage')?60:40})).sort((x,y)=>y.score-x.score);a.choose(ranked[0].i);choices++;}
 if(['won','lost'].includes(a.state))break;a.step(.05);
 }
 assert.ok(['won','lost'].includes(a.state),'run must end');assert.ok(a.team.length<=4);assert.ok(Number.isFinite(a.hp));assert.ok(choices>4);console.log(JSON.stringify({hero,state:a.state,wave:a.wave,kills:a.kills,choices,team:a.team.length,time:Math.round(a.time),hp:Math.round(a.hp)}));
}
const p=new Game();p.addHero(1);p.addHero(2);p.addHero(3);for(let i=0;i<40;i++){const opts=p.makeOptions();assert.ok(opts.every(o=>!o.id.startsWith('recruit')))}
const one=new Game({random:rng()}),two=new Game({random:rng()});for(let i=0;i<100;i++)one.step(.01);for(let i=0;i<50;i++){two.step(.01);two.step(.01)}assert.equal(one.time,two.time);assert.equal(one.hp,two.hp);
console.log('PASS: manual pause, 3 unique valid options, recruitment, full-team filters, four complete runs, speed stepping.');
const upgraded=new Game({meta:{power:8,vitality:8,reload:8},random:rng()});for(let i=0;i<90000;i++){if(upgraded.state==='upgrade'){let r=upgraded.options.findIndex(o=>o.id.startsWith('recruit'));if(r<0)r=upgraded.options.findIndex(o=>o.id==='wall'&&upgraded.hp/upgraded.maxHp<.6);if(r<0)r=upgraded.options.findIndex(o=>o.id==='team'||o.id.startsWith('damage'));upgraded.choose(Math.max(0,r));}if(['won','lost'].includes(upgraded.state))break;upgraded.step(.05)}assert.equal(upgraded.state,'won','progression must make a winning run reachable');console.log('PASS: upgraded team wins final boss.');
const targeting=new Game();targeting.enemies=[{id:1,type:0,x:120,y:400,hp:100,maxHp:100,speed:0,damage:1,attack:1,burn:0,slow:0,flash:0},{id:2,type:0,x:160,y:200,hp:100,maxHp:100,speed:0,damage:1,attack:1,burn:0,slow:0,flash:0}];targeting.target=2;targeting.team[0].cd=0;targeting.step(.01);assert.equal(targeting.projectiles[0].targetId,2);assert.equal(targeting.enemies[1].hp,100);for(let i=0;i<12;i++)targeting.step(.01);assert.equal(targeting.enemies[0].hp,100);assert.ok(targeting.enemies[1].hp<100);targeting.target=null;targeting.team[0].cd=0;targeting.step(.01);assert.equal(targeting.projectiles[0].targetId,1);for(let i=0;i<8;i++)targeting.step(.01);assert.ok(targeting.enemies[0].hp<100);console.log('PASS: manual target overrides nearest, clearing restores default.');
const fence=new Game();fence.shield=5;fence.enemies=[{id:1,type:0,x:100,y:523,hp:999,maxHp:999,speed:0,damage:10,attack:0,burn:0,slow:0,flash:0}];fence.step(.01);assert.equal(fence.shield,0);assert.equal(fence.hp,fence.maxHp-5);assert.ok(fence.team.every(h=>h.hp===undefined));console.log('PASS: shield absorbs before fence health, heroes have no health.');
const {startingChoices,HOUSES}=await import('./dist/engine.js');assert.equal(HOUSES.length,1);for(let i=0;i<30;i++){const c=startingChoices();assert.equal(c.length,3);assert.equal(new Set(c).size,3);assert.ok(c.every(v=>v>=0&&v<4));}
for(const wave of [3,6,10]){const a=new Game();a.wave=wave;a.spawnTotal=7+wave*3;a.spawn();assert.equal(a.enemies[0].isBoss,true);assert.ok(a.enemies[0].bossName);a.spawn();assert.equal(a.enemies[1].isBoss,false);}
const progressGame=new Game();progressGame.wave=2;progressGame.spawnTotal=10;progressGame.waveKills=5;progressGame.step(.01);assert.equal(progressGame.progress,.5);progressGame.state='upgrade';let xpBefore=progressGame.xp,elapsed=progressGame.time;progressGame.step(.1);assert.equal(progressGame.xp,xpBefore);assert.equal(progressGame.time,elapsed);
for(let i=0;i<100;i++){const a=new Game({hero:i%4});a.makeOptions().filter(o=>['אישי','יכולת'].includes(o.kind)).forEach(o=>assert.ok(o.who.includes(a.team[0].name)));}
console.log('PASS: one house, 3 distinct random starters, bosses at 3/6/10, kill-based wave progress, owned hero eligibility.');
