import assert from 'node:assert/strict';
import {Game} from './dist/engine.js';
import {SHOCKWAVE} from './dist/shockwave.js';
const fixture=()=>{const g=new Game({random:()=>.5});g.intermission=100;g.nextXp=1e9;g.team[0].cd=100;g.enemies=[510,270,100,20].map((y,type)=>({id:type+1,type,isBoss:type===3,x:100+type*100,y,hp:10000,maxHp:10000,speed:0,damage:0,attack:1,burn:0,slow:0,flash:0}));return g;};
const g=fixture();g.activateShockwave();for(let i=0;i<150;i++)g.step(.01);assert.equal(g.shockwave.front,0,'front reaches full playable lane end');assert.deepEqual(g.enemies.map(e=>e.y),[430,178,68,13.6]);assert(g.enemies.every(e=>e.hp===10000));assert.equal(g.loot.length,0);assert.equal(g.kills,0);assert.equal(g.shockwave.hitIds.size,0);
for(const speed of [1,2,3]){const a=fixture();a.activateShockwave();for(let frame=0;frame<150/speed;frame++)for(let n=0;n<speed;n++)a.step(.01);assert.deepEqual(a.enemies,g.enemies);}
const empty=fixture();empty.enemies=[];empty.activateShockwave();empty.step(.1);empty.state='paused';const age=empty.shockwave.age;empty.step(.1);assert.equal(empty.shockwave.age,age);empty.state='playing';for(let i=0;i<150;i++)empty.step(.01);assert.equal(empty.shockwave.front,0,'empty lane still receives full travelling front');
console.log('PASS M5.1: full-lane zero-damage Shockwave, all mass classes, deterministic speeds, pause and empty lane.');
import {FloatingFeedback} from './dist/floating-feedback.js';
import {SpecialChoreography} from './dist/special-choreography.js';
import {feedbackState} from './dist/damage-feedback.js';
import * as T from './dist/vendor/three.module.js';
let created=0,removed=0;globalThis.document={createElement:()=>{created++;return {style:{},setAttribute(){},remove(){removed++}}}};
const pool=new FloatingFeedback({append(){}},12);for(let i=0;i<100;i++)pool.fly({kind:'xp',value:3,x:0,y:10,tx:200,ty:400,time:0});assert.equal(pool.active,12);assert.equal(created,12);pool.update(.2);const pose=pool.slots[0].el.style.transform;pool.update(.2);assert.equal(pool.slots[0].el.style.transform,pose,'paused reward motion stable');pool.update(.6);assert.equal(pool.active,0);for(let i=0;i<100;i++){pool.fly({kind:'coin',value:2,x:1,y:1,tx:100,ty:100,time:i});pool.update(i+.6);}assert.equal(created,12);pool.reset();pool.dispose();pool.dispose();assert.equal(removed,12);
const scene=new T.Scene(),special=new SpecialChoreography(scene),actor=new T.Group(),body=new T.Group(),muzzle=new T.Object3D();body.add(muzzle);actor.add(body);actor.userData={body,muzzle};const actors=new Map([[0,actor]]),state={time:1,team:[{id:'electric',color:'#aaffee'}],powerCharge:8,powerNeeded:8,effects:[]};special.update(state,actors);special.arm(0,1);special.update(state,actors);assert(special.rigs[0].root.visible);const geometry=special.rigs[0].shards.geometry;state.effects=[{type:'special',presentation:{heroId:'electric',special:2},life:.65,maxLife:.65}];state.time=1.1;special.update(state,actors);assert.equal(special.rigs[0].shards.geometry,geometry);state.powerCharge=0;state.effects=[];state.time=2.2;special.update(state,actors);assert.equal(special.active,0);special.update(null,actors);special.dispose();special.dispose();assert.equal(scene.children.length,0);assert.equal(feedbackState({text:'42'}),'normal');assert.equal(feedbackState({text:'42',critical:true}),'critical');
console.log('PASS M5.1: bounded reusable reward nodes, pause/reset/disposal, reserved elemental rigs and truthful critical classification.');
import {observeHit} from './dist/combat-presentation.js';
const runner=fixture();runner.enemies=[{...runner.enemies[1],id:99,y:500,speed:60}];runner.activateShockwave();for(let i=0;i<9;i++)runner.step(.05);const reacting=new T.Group();observeHit(reacting,runner.enemies[0],runner.effects,runner.time,new T.Vector3(),runner.shockwave);assert.equal(reacting.userData.waveAt,runner.time,'moving runner reaction uses actual per-wave contact, not stale impact coordinates');
